### ISSUE TITLE
Entity & 연관관계매핑 확인

### ISSUE THREAD

**Issue by woojin0906** [woojin0906/walkingMate_Back#2]
Entity & 연관관계매핑 수정한 부분 노션에 작성해두었습니다.

- [x] 각 엔티티별 컬럼 확인(기본키, 데이터타입)
- [x] 연관관계매핑 확인

 잘 되었는지 확인 부탁드립니다.

**Comment by Lib0823** [comment]
최종 확인 완료했고, 혹시 나중에 FK설정 문제있으면 @JoinColumn()속성 referencedColumnName = "참조할 컬럼명" 추가 부탁드립니다.
